# Tanda 2 — Gestion de citas: CU17, CU18, CU22, CU76.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from motor import generar_cu, chrome_path
from comun import *

# ──────────────────────────── CU17 ────────────────────────────
CU17 = dict(id='CU17', nombre='Gestionando reprogramación de cita', actores=['Paciente'],
  vistas={'Paciente': 'V_Agendamiento_Cita'},
  participantes=[ACTOR, VISTA, *capa(), *T('Cita', 'Bloqueo_Agenda', 'Parametro_Global', 'Bitacora_Auditoria', 'Notificacion')],
  principal=[
    'A -> V: seleccionar_reprogramar_cita(cita_id)',
    'V ->> V: verificar_estado_reprogramable()',
    'V --> A: solicitar_motivo_del_cambio()',
    'A -> V: indicar_motivo(motivo)',
    f'V -> {API}: GET /citas/disponibilidad (profesional_id, fecha)',
    *leer('consultar_cupos_disponibles(profesional_id, fecha)', 'Cita', 'cita_id, fecha_hora_inicio, fecha_hora_fin, estado', 'bloques ocupados', 'return (matriz de disponibilidad)'),
    f'{API} --> V: return (HTTP 200 OK: cupos disponibles)',
    'V --> A: mostrar_matriz_de_disponibilidad()',
    'A -> V: seleccionar_nuevo_bloque(fecha_hora_inicio)',
    f'V -> {API}: POST /citas/:id/reprogramar (nuevo_bloque, motivo)',
    *begin(),
    *leer('bloquear_y_leer_cita(cita_id)', 'Cita', 'cita_id, estado, fecha_hora_inicio, fecha_hora_fin, paciente_id', '1 cita', 'return (cita)'),
    f'{API} ->> {API}: verificar_estado_y_titularidad()',
    *leer('leer_parametro(HORAS_MIN_REPROGRAMACION)', 'Parametro_Global', 'clave, valor', 'horas minimas', 'return (horas_minimas)'),
    f'{API} ->> {API}: validar_anticipacion_minima()',
    *leer('verificar_bloque_libre(nuevo_bloque)', 'Cita', 'cita_id', '0 citas en el bloque', 'return (bloque libre)'),
    *leer('verificar_bloqueos_de_agenda(profesional_id, nuevo_bloque)', 'Bloqueo_Agenda', 'bloqueo_id, motivo', '0 bloqueos', 'return (sin bloqueos)'),
    *actualizar('actualizar_horario(cita_id, nuevo_bloque, AGENDADA)', 'Cita', 'fecha_hora_inicio, fecha_hora_fin, estado'),
    *insertar('registrar_trazabilidad(CITA_REPROGRAMADA, bloque_anterior, bloque_nuevo, motivo)', 'Bitacora_Auditoria'),
    *insertar('notificar_a_ambos_participantes(CITA_REPROGRAMADA)', 'Notificacion', ' (aviso de reprogramacion)'),
    *commit(),
    f'{API} --> V: return (HTTP 200 OK: cita reprogramada)',
    'V --> A: mostrar_confirmacion_con_la_nueva_fecha()',
  ],
  excepciones={
    1: dict(cortar='verificar_estado_reprogramable', lineas=['! La cita ya esta realizada, cancelada, con inasistencia o en curso',
        'V --> A: deshabilitar_controles_de_edicion()', 'A -> V: volver_al_listado_principal()', 'V --> A: mostrar_citas_activas()'],
        reanudar='seleccionar_reprogramar_cita'),
    2: dict(cortar='validar_anticipacion_minima', lineas=['! Solicitud fuera del tiempo minimo de anticipacion configurado',
        *rollback(), f'{API} --> V: return (HTTP 409 FUERA_DE_PLAZO)',
        'V --> A: notificar_restriccion_temporal_y_denegar_calendario()',
        'A ->> A: gestionar_la_autorizacion_con_soporte_administrativo()'], reanudar='seleccionar_reprogramar_cita'),
    3: dict(cortar='SELECT cita_id FROM Cita', lineas=[*vacio('Cita', '1 cita tomada por otro proceso', 'bloque ocupado'),
        '! El bloque fue tomado por otra reserva o cae en un bloqueo de agenda',
        *rollback(), f'{API} --> V: return (HTTP 409 BLOQUE_OCUPADO | AGENDA_BLOQUEADA)',
        'V --> A: refrescar_matriz_de_disponibilidad()'], reanudar='seleccionar_nuevo_bloque'),
    4: dict(cortar='INSERT INTO Notificacion (aviso de reprogramacion)', lineas=[*fallo_bd('Notificacion', 'servicio de notificaciones no disponible'),
        '! Falla el aviso tras guardar: la cita ya quedo reprogramada',
        f'{API} ->> {API}: registrar_error_de_comunicacion()'], reanudar='confirmar_transaccion'),
  })

# ──────────────────────────── CU18 ────────────────────────────
CU18 = dict(id='CU18', nombre='Cancelando cita y liberando recursos', actores=['Paciente', 'Profesional'],
  vistas={'Paciente': 'V_Mis_Citas', 'Profesional': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *capa(), *T('Cita', 'Parametro_Global', 'Bitacora_Auditoria', 'Lista_Espera', 'Notificacion')],
  principal=[
    'A -> V: solicitar_anulacion_de_cita(cita_id)',
    'V --> A: mostrar_dialogo_de_confirmacion()',
    'A -> V: ratificar_anulacion(motivo)',
    'V ->> V: verificar_motivo_no_vacio()',
    f'V -> {API}: POST /citas/:id/transicionar (evento = CANCELAR, motivo)',
    *begin(),
    *leer('bloquear_y_leer_cita(cita_id)', 'Cita', 'cita_id, estado, fecha_hora_inicio, paciente_id, profesional_id', '1 cita', 'return (cita)'),
    f'{API} ->> {API}: verificar_titularidad_del_actor({{A}})',
    *leer('leer_parametro(HORAS_MIN_CANCELACION)', 'Parametro_Global', 'clave, valor', 'horas minimas', 'return (horas_minimas)'),
    f'{API} ->> {API}: validar_plazo_minimo_de_anticipacion()',
    f'{API} ->> {API}: evaluar_maquina_de_estados(CANCELAR, rol = {{A}})',
    *actualizar('actualizar_estado(CANCELADA_{A_MAY}, motivo)', 'Cita', 'estado, motivo_cancelacion'),
    *insertar('registrar_trazabilidad(CITA_CANCELADA, rol_actor, motivo)', 'Bitacora_Auditoria'),
    *insertar('notificar_a_ambos_participantes(CAMBIO_ESTADO_CITA)', 'Notificacion', ' (aviso de cancelacion)'),
    *leer('buscar_inscritos_en_lista_de_espera(cita_id)', 'Lista_Espera', 'lista_espera_id, posicion, usuario_id', 'N inscritos', 'return (inscritos)'),
    *bloque('avisar_cupo_liberado(inscritos)', [ins('Notificacion', ' (cupo liberado)'), upd('Lista_Espera', 'notificado')], 'return (cupos_notificados)'),
    *commit(),
    f'{API} --> V: return (HTTP 200 OK: cita cancelada, cupos_notificados)',
    'V --> A: mostrar_confirmacion_y_cronograma_actualizado()',
  ],
  excepciones={
    1: dict(cortar='validar_plazo_minimo_de_anticipacion', lineas=['! Anulacion fuera del plazo reglamentario parametrizado',
        *rollback(), f'{API} --> V: return (HTTP 409 FUERA_DE_PLAZO)',
        'V --> A: informar_imposibilidad_de_cancelar_con_poca_antelacion()',
        'A ->> A: gestionar_la_anulacion_directamente_con_el_centro()'], reanudar='solicitar_anulacion_de_cita'),
    2: dict(cortar='UPDATE Cita SET estado, motivo_cancelacion', lineas=[*fallo_bd('Cita'),
        '! Fallo de persistencia al actualizar la cita',
        *rollback(), f'{API} --> V: return (HTTP 500: la anulacion no pudo completarse)',
        'V --> A: solicitar_reintento_manual()', 'A -> V: ratificar_anulacion(motivo)'], reanudar='verificar_motivo_no_vacio'),
    3: dict(cortar='return (HTTP 200 OK: cita cancelada', lineas=['! La vista no logra renderizar el resumen de la operacion',
        'V ->> V: registrar_error_de_carga_en_el_cliente()', 'V --> A: mostrar_pantalla_incompleta()',
        'A -> V: refrescar_la_aplicacion()', f'V -> {API}: GET /citas/mis-citas',
        *leer('listar_citas_del_actor(usuario_id)', 'Cita', 'cita_id, fecha_hora_inicio, estado', 'N citas', 'return (citas)'),
        f'{API} --> V: return (HTTP 200 OK: listado actualizado)'], reanudar='mostrar_confirmacion_y_cronograma_actualizado'),
    4: dict(cortar='INSERT INTO Notificacion (cupo liberado)', lineas=[*fallo_bd('Notificacion', 'servicio de notificaciones no disponible'),
        '! Falla el aviso a la lista de espera: la cancelacion se mantiene',
        f'{API} ->> {API}: registrar_fallo_de_notificacion()'], reanudar='confirmar_transaccion'),
  })

# ──────────────────────────── CU22 ────────────────────────────
CU22 = dict(id='CU22', nombre='Registrando trazabilidad de transiciones de agenda', actores=TRES,
  vistas={'Paciente': 'V_Mis_Citas', 'Profesional': 'V_Gestion_Agenda', 'Administrador': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *capa(), *T('Cita', 'Bitacora_Auditoria')],
  principal=[
    'A -> V: ejecutar_cambio_de_estado_o_reprogramacion(cita_id, motivo)',
    f'V -> {API}: POST /citas/:id/transicionar (evento, motivo)',
    f'{API} ->> {API}: verificar_token_y_obtener_actor(usuario_id, rol = {{A}})',
    *begin(),
    *leer('bloquear_y_leer_cita(cita_id)', 'Cita', 'cita_id, estado, paciente_id, profesional_id', '1 cita', 'return (cita)'),
    f'{API} ->> {API}: verificar_estado_no_terminal()',
    f'{API} ->> {API}: capturar_metadatos(usuario_id, rol, momento_evento, ip_origen)',
    f'{API} ->> {API}: exigir_justificacion_en_cancelacion_o_reprogramacion()',
    *actualizar('aplicar_cambio_de_estado(nuevo_estado)', 'Cita', 'estado, motivo_cancelacion'),
    *insertar('registrar_trazabilidad(accion, responsable, rol, motivo, ip_origen)', 'Bitacora_Auditoria', ' (accion, entidad_afectada, ip_origen, datos_adicionales, usuario_id)'),
    *commit(),
    f'{API} --> V: return (HTTP 200 OK: cambio aplicado y trazado)',
    'V --> A: mostrar_estado_actualizado()',
    'A -> V: consultar_trazabilidad_de_la_cita(cita_id)',
    f'V -> {API}: GET /citas/:id/trazabilidad',
    *leer('obtener_historial_de_la_cita(cita_id)', 'Bitacora_Auditoria', 'accion, momento_evento, datos_adicionales, usuario_id', 'N eventos', 'return (eventos del mas reciente al mas antiguo)'),
    f'{API} --> V: return (HTTP 200 OK: historial de la cita)',
    'V --> A: desplegar_responsable_motivo_y_fecha_de_cada_cambio()',
  ],
  excepciones={
    1: dict(cortar='verificar_estado_no_terminal', lineas=['! La cita ya posee un estado terminal no modificable',
        *rollback(), f'{API} --> V: return (HTTP 409 ESTADO_TERMINAL)',
        'V --> A: bloquear_edicion_y_mostrar_restriccion_de_flujo()'], reanudar='ejecutar_cambio_de_estado_o_reprogramacion'),
    2: dict(cortar='verificar_token_y_obtener_actor', lineas=['! Perdida de contexto de la sesion: no se identifica al responsable',
        f'{API} ->> {API}: omitir_la_modificacion_de_la_cita()', f'{API} --> V: return (HTTP 401: advertencia de seguridad)',
        'V --> A: mostrar_advertencia_y_cerrar_sesion()', 'A ->> A: reiniciar_sesion_para_recuperar_credenciales()'],
        reanudar='ejecutar_cambio_de_estado_o_reprogramacion'),
    3: dict(cortar='exigir_justificacion_en_cancelacion_o_reprogramacion', lineas=['! Campo de justificacion vacio en una cancelacion o reprogramacion',
        *rollback(), f'{API} --> V: return (HTTP 400 MOTIVO_REQUERIDO)',
        'V --> A: impedir_la_transicion_y_resaltar_campo_obligatorio()'], reanudar='ejecutar_cambio_de_estado_o_reprogramacion'),
    4: dict(cortar='INSERT INTO Bitacora_Auditoria (accion', lineas=[*fallo_bd('Bitacora_Auditoria'),
        '! Fallo de persistencia durante el registro del log',
        *rollback(), f'{API} --> V: return (HTTP 500: el cambio no pudo aplicarse)',
        'V --> A: notificar_que_el_cambio_no_se_aplico()'], reanudar='ejecutar_cambio_de_estado_o_reprogramacion'),
  })

# ──────────────────────────── CU76 ────────────────────────────
CU76 = dict(id='CU76', nombre='Ejecutando transacciones en máquina de estados de la cita', actores=['Profesional'],
  vistas={'Profesional': 'V_Gestion_Agenda'},
  participantes=[ACTOR, VISTA, *capa(), *T('Cita', 'Profesional', 'Paquete_Sesiones', 'Bitacora_Auditoria', 'Notificacion')],
  principal=[
    'A -> V: seleccionar_cita_en_historial_del_paciente(cita_id)',
    'V ->> V: verificar_cita_propia_y_estado_no_terminal()',
    'V --> A: desplegar_acciones_de_transicion_habilitadas()',
    'A -> V: ejecutar_transicion(FINALIZAR)',
    f'V -> {API}: POST /citas/:id/transicionar (evento = FINALIZAR)',
    *begin(),
    *leer('bloquear_y_leer_cita(cita_id)', 'Cita', 'cita_id, estado, paciente_id, profesional_id', '1 cita', 'return (cita)'),
    *leer('verificar_titularidad_del_profesional(usuario_id)', 'Profesional', 'profesional_id, usuario_id', '1 coincidencia', 'return (cita propia)'),
    f'{API} ->> {API}: evaluar_maquina_de_estados(CONFIRMADA | EN_CURSO -> REALIZADA)',
    *actualizar('actualizar_estado(REALIZADA | INASISTENCIA)', 'Cita', 'estado'),
    *bloque('descontar_sesion_del_paquete(paciente_id)', [q('Paquete_Sesiones', 'paquete_sesiones_id, sesiones_total, sesiones_usadas', '1 paquete activo'), upd('Paquete_Sesiones', 'sesiones_usadas')], 'return (sesiones_restantes)'),
    *insertar('registrar_trazabilidad(CITA_TRANSICIONADA, evento, responsable)', 'Bitacora_Auditoria'),
    *insertar('notificar_a_ambos_participantes(CAMBIO_ESTADO_CITA)', 'Notificacion', ' (aviso de cambio de estado)'),
    *commit(),
    f'{API} --> V: return (HTTP 200 OK: estado actualizado e inventario)',
    'V --> A: mostrar_estado_de_la_cita_y_sesiones_restantes()',
  ],
  excepciones={
    1: dict(cortar='verificar_cita_propia_y_estado_no_terminal', lineas=['! La cita pertenece a otro profesional',
        'V --> A: mostrar_cita_bloqueada_sin_controles_de_transicion()'], reanudar='seleccionar_cita_en_historial_del_paciente'),
    2: dict(cortar='verificar_cita_propia_y_estado_no_terminal', lineas=['! La cita ya posee un estado terminal',
        'V --> A: bloquear_modificaciones_y_mostrar_solo_lectura()'], reanudar='seleccionar_cita_en_historial_del_paciente'),
    3: dict(cortar='desplegar_acciones_de_transicion_habilitadas', lineas=['! El paciente no se presenta a la atencion',
        'A -> V: registrar_inasistencia()', f'V -> {API}: POST /citas/:id/transicionar (evento = REGISTRAR_INASISTENCIA)',
        f'{API} ->> {API}: aplicar_penalizacion_descontando_igualmente_la_sesion()'], reanudar='abrir_transaccion'),
    4: dict(cortar='SELECT paquete_sesiones_id', lineas=[*vacio('Paquete_Sesiones', '0 paquetes activos', 'sin paquete activo'),
        '! El paciente no posee un paquete de sesiones activo',
        f'{API} ->> {API}: omitir_la_sustraccion_de_la_sesion()'], reanudar='registrar_trazabilidad(CITA_TRANSICIONADA'),
  })

if __name__ == '__main__':
    chrome = chrome_path()
    salida = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'salida')
    total = 0
    for cu in [CU17, CU18, CU22, CU76]:
        ruta, n = generar_cu(cu, os.path.join(salida, cu['id']), chrome=chrome, png=True)
        total += n; print(f"{cu['id']}: {n} paginas")
    print('total paginas', total)
