# Tanda 1 — Cuenta, seguridad, perfil y segregacion por rol: CU06, CU07, CU08, CU09, CU10, CU79.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from motor import generar_cu, chrome_path
from comun import *

VREC, VSEG = 'V_Recuperar_Contrasena', 'V_Seguridad_Cuenta'

# ──────────────────────────── CU06 ────────────────────────────
CU06 = dict(id='CU06', nombre='Solicitando restablecimiento de credenciales', actores=TRES,
  vistas={r: VREC for r in TRES},
  participantes=[ACTOR, VISTA, *capa(ADP, BREVO), *T('Usuario')],
  principal=[
    'A -> V: acceder_a_olvide_mi_contrasena()',
    'V --> A: desplegar_formulario_de_correo()',
    'A -> V: ingresar_correo(email)',
    'V ->> V: validar_formato_del_correo()',
    f'V -> {API}: POST /auth/recuperar/solicitar (email)',
    *leer('buscar_usuario_por_email(email)', 'Usuario', 'usuario_id, email', '1 coincidencia', 'return (usuario)'),
    f'{API} ->> {API}: generar_otp(6 digitos, vigencia 10 min)',
    *actualizar('guardar_otp(usuario_id, codigo, expiracion)', 'Usuario', 'otp_codigo, otp_expiracion'),
    *externo('enviar_correo(email, codigo_otp)', BREVO, 'POST /v3/smtp/email', 'return (HTTP 201 Aceptado)', 'return (correo aceptado)'),
    f'{API} --> V: return (HTTP 200 OK: si el correo existe se envio un codigo)',
    'V --> A: mostrar_mensaje_de_codigo_enviado()',
  ],
  excepciones={
    1: dict(cortar='acceder_a_olvide', lineas=['! Error de redireccionamiento interno del enlace de recuperacion',
        'V ->> V: registrar_fallo_de_navegacion()', 'V --> A: mostrar_servicio_no_disponible_momentaneamente()',
        'A -> V: reintentar_el_acceso_pasados_unos_minutos()'], reanudar='desplegar_formulario_de_correo'),
    2: dict(cortar='acceder_a_olvide', lineas=['! Sin conexion con el servidor de aplicaciones: tiempo de espera agotado',
        'V --> A: mostrar_alerta_de_tiempo_de_espera_agotado()', 'A -> V: recargar_la_aplicacion()'], reanudar='desplegar_formulario_de_correo'),
    3: dict(cortar='validar_formato_del_correo', lineas=['! Dominio de correo invalido o incompleto',
        'V --> A: bloquear_envio_y_resaltar_error_sintactico()', 'A -> V: corregir_el_correo(email)'], reanudar='validar_formato_del_correo'),
    4: dict(cortar='SELECT usuario_id, email FROM Usuario', lineas=[*vacio('Usuario', '0 coincidencias', 'sin usuario'),
        '! Correo no registrado: se simula el despacho para evitar enumeracion de usuarios',
        f'{API} ->> {API}: omitir_envio_de_codigo()',
        f'{API} --> V: return (HTTP 200 OK: si el correo existe se envio un codigo)', 'V --> A: mostrar_mensaje_de_codigo_enviado()'],
        reanudar='ingresar_correo'),
  })

# ──────────────────────────── CU07 ────────────────────────────
CU07 = dict(id='CU07', nombre='Ejecutando cambio de contraseña', actores=TRES,
  vistas={r: VREC for r in TRES},
  participantes=[ACTOR, VISTA, *capa(SEG, ADP, BREVO), *T('Usuario', 'Sesion_Usuario', 'Bitacora_Auditoria')],
  principal=[
    'A -> V: ingresar_codigo_otp(codigo)',
    'V ->> V: validar_mascara_numerica(codigo)',
    'V --> A: habilitar_formulario_de_nueva_contrasena()',
    'A -> V: escribir_nueva_contrasena(nueva_contrasena, confirmacion)',
    'V ->> V: validar_robustez_de_la_contrasena(8+, letra, numero, simbolo)',
    f'V -> {API}: POST /auth/recuperar/confirmar (email, codigo, nueva_contrasena)',
    *leer('obtener_usuario_y_otp(email)', 'Usuario', 'usuario_id, otp_codigo, otp_expiracion', '1 registro', 'return (usuario)'),
    f'{API} ->> {API}: comparar_codigo_y_vigencia(codigo)',
    f'{API} ->> {API}: validar_robustez_de_la_contrasena()',
    f'{API} -> {SEG}: cifrar_contrasena(bcrypt)',
    f'{SEG} --> {API}: return (contrasena_hash)',
    *begin(),
    *actualizar('actualizar_contrasena(usuario_id, hash)', 'Usuario', 'contrasena_hash, otp_codigo, otp_expiracion'),
    *actualizar('revocar_todas_las_sesiones(usuario_id)', 'Sesion_Usuario', 'activa', 'return (sesiones revocadas)'),
    *insertar('registrar_auditoria(CONTRASENA_CAMBIADA, usuario_id, ip)', 'Bitacora_Auditoria'),
    *commit(),
    f'{API} --> V: return (HTTP 200 OK: contrasena actualizada)',
    'V --> A: mostrar_exito_y_redirigir_a_inicio_de_sesion()',
  ],
  excepciones={
    1: dict(cortar='validar_mascara_numerica', lineas=['! Caracteres alfabeticos en un campo que solo admite digitos',
        'V --> A: bloquear_entrada_con_mascara_de_validacion()', 'A -> V: corregir_codigo_solo_digitos(codigo)'], reanudar='validar_mascara_numerica'),
    2: dict(cortar='comparar_codigo_y_vigencia', lineas=['! El codigo no coincide con el registro activo o expiro',
        f'{API} --> V: return (HTTP 400 CODIGO_INVALIDO)', 'V --> A: mostrar_alerta_de_codigo_invalido()',
        'A -> V: solicitar_reenvio_del_codigo()', f'V -> {API}: POST /auth/recuperar/solicitar (email)',
        *leer('buscar_usuario_por_email(email)', 'Usuario', 'usuario_id, email', '1 coincidencia', 'return (usuario)'),
        f'{API} ->> {API}: generar_otp(6 digitos, vigencia 10 min)',
        *actualizar('guardar_otp(usuario_id, codigo, expiracion)', 'Usuario', 'otp_codigo, otp_expiracion'),
        *externo('enviar_correo(email, codigo_otp)', BREVO, 'POST /v3/smtp/email', 'return (HTTP 201 Aceptado)', 'return (correo aceptado)'),
        f'{API} --> V: return (HTTP 200 OK: nuevo codigo enviado)', 'V --> A: mostrar_mensaje_de_codigo_enviado()'],
        reanudar='ingresar_codigo_otp'),
    3: dict(cortar='validar_robustez_de_la_contrasena(8+', lineas=['! Contrasena sin la robustez exigida (8+ caracteres, letras, numeros y un simbolo)',
        'V --> A: resaltar_requisitos_incumplidos_y_deshabilitar_confirmar()', 'A -> V: modificar_la_contrasena(nueva_contrasena)'],
        reanudar='validar_robustez_de_la_contrasena(8+'),
    4: dict(cortar='UPDATE Usuario SET contrasena_hash', lineas=[*fallo_bd('Usuario', 'interrupcion de conexion'),
        '! Interrupcion de la comunicacion con el servidor de datos durante el guardado',
        *rollback(), f'{API} ->> {API}: registrar_fallo_de_persistencia()',
        f'{API} --> V: return (HTTP 500: operacion no completada)', 'V --> A: notificar_operacion_no_completada()',
        'A -> V: reintentar_el_envio_del_formulario()'], reanudar='POST /auth/recuperar/confirmar'),
  })

# ──────────────────────────── CU08 ────────────────────────────
CU08 = dict(id='CU08', nombre='Gestionando sesiones y tokens de acceso', actores=TRES,
  vistas={r: VSEG for r in TRES},
  participantes=[ACTOR, VISTA, *capa(), *T('Sesion_Usuario')],
  principal=[
    'A -> V: acceder_a_seguridad_de_la_cuenta()',
    f'V -> {API}: GET /auth/sesiones',
    *leer('listar_sesiones_activas(usuario_id)', 'Sesion_Usuario', 'sesion_id, jti, dispositivo, ip, creada_en', 'N sesiones', 'return (sesiones)'),
    f'{API} ->> {API}: marcar_la_sesion_actual(jti del token)',
    f'{API} --> V: return (HTTP 200 OK: lista de sesiones)',
    'V --> A: desplegar_sesiones_activas(dispositivo, ip, fecha_inicio)',
    'A -> V: revocar_sesion(sesion_id)',
    f'V -> {API}: POST /auth/sesiones/:id/cerrar',
    *actualizar('desactivar_sesion(sesion_id, usuario_id)', 'Sesion_Usuario', 'activa'),
    f'{API} --> V: return (HTTP 200 OK: sesion cerrada)',
    'V --> A: actualizar_la_lista_sin_el_dispositivo()',
  ],
  excepciones={
    1: dict(cortar='acceder_a_seguridad', lineas=['! Error de ruteo en la aplicacion al abrir los ajustes de seguridad',
        'V --> A: mostrar_error_de_navegacion()', 'A -> V: recargar_la_aplicacion()'], reanudar='GET /auth/sesiones'),
    2: dict(cortar='SELECT sesion_id', lineas=[*fallo_bd('Sesion_Usuario', 'tiempo de espera agotado'),
        '! El servicio de identidades no logra recuperar las sesiones',
        f'{API} --> V: return (HTTP 500: sesiones no disponibles)', 'V --> A: mostrar_advertencia_de_dispositivos_no_disponibles()',
        'A -> V: presionar_actualizar_manualmente()'], reanudar='GET /auth/sesiones'),
    3: dict(cortar='UPDATE Sesion_Usuario SET activa', lineas=[*vacio('Sesion_Usuario', 'confirmacion_update, 0 filas', 'sesion no activa'),
        '! La sesion ya habia expirado o fue cerrada mientras se veia la lista',
        f'{API} --> V: return (HTTP 404 SESION_NO_ACTIVA)', 'V --> A: notificar_que_la_sesion_ya_no_esta_activa()',
        'A -> V: refrescar_la_lista()', f'V -> {API}: GET /auth/sesiones',
        *leer('listar_sesiones_activas(usuario_id)', 'Sesion_Usuario', 'sesion_id, jti, dispositivo, ip, creada_en', 'N sesiones', 'return (sesiones)'),
        f'{API} ->> {API}: marcar_la_sesion_actual(jti del token)',
        f'{API} --> V: return (HTTP 200 OK: lista actualizada)', 'V --> A: desplegar_sesiones_activas(dispositivo, ip, fecha_inicio)'],
        reanudar='revocar_sesion'),
    4: dict(cortar='UPDATE Sesion_Usuario SET activa', lineas=[*fallo_bd('Sesion_Usuario'),
        '! Falla de persistencia al desactivar el registro de sesion',
        f'{API} ->> {API}: registrar_la_excepcion()', f'{API} --> V: return (HTTP 500: reintente la operacion)',
        'V --> A: solicitar_reintento()'], reanudar='revocar_sesion'),
  })

# ──────────────────────────── CU09 ────────────────────────────
CU09 = dict(id='CU09', nombre='Configurando privacidad de datos de contacto', actores=['Paciente'],
  vistas={'Paciente': VSEG},
  participantes=[ACTOR, VISTA, *capa(), *T('Paciente', 'Bitacora_Auditoria')],
  principal=[
    'A -> V: abrir_el_modulo_de_privacidad()',
    f'V -> {API}: GET /auth/privacidad',
    *leer('obtener_privacidad(usuario_id)', 'Paciente', 'privacidad_contacto', '1 registro', 'return (privacidad_contacto)'),
    f'{API} --> V: return (HTTP 200 OK: mostrar_direccion, mostrar_telefono)',
    'V --> A: desplegar_la_matriz_de_visibilidad()',
    'A -> V: ajustar_interruptores_y_guardar(mostrar_direccion, mostrar_telefono)',
    f'V -> {API}: PUT /auth/privacidad (mostrar_direccion, mostrar_telefono)',
    f'{API} ->> {API}: validar_valores_booleanos()',
    *actualizar('actualizar_privacidad(usuario_id, preferencias)', 'Paciente', 'privacidad_contacto'),
    *insertar('registrar_auditoria(PRIVACIDAD_ACTUALIZADA, usuario_id, ip)', 'Bitacora_Auditoria'),
    f'{API} --> V: return (HTTP 200 OK: preferencias guardadas)',
    'V --> A: mostrar_preferencias_guardadas()',
  ],
  excepciones={
    1: dict(cortar='abrir_el_modulo_de_privacidad', lineas=['! Modulo de privacidad no disponible por falla del servidor de aplicaciones',
        'V --> A: mostrar_error_de_carga_del_componente()', 'A -> V: recargar_la_aplicacion()'], reanudar='GET /auth/privacidad'),
    2: dict(cortar='return (HTTP 200 OK: mostrar_direccion', lineas=['! Fallo de interfaz: los interruptores no se despliegan',
        'V ->> V: registrar_error_de_ejecucion()', 'V --> A: mostrar_pantalla_incompleta()', 'A -> V: reiniciar_la_aplicacion()'],
        reanudar='GET /auth/privacidad'),
    3: dict(cortar='validar_valores_booleanos', lineas=['! Valores invalidos (no booleanos) en las opciones de privacidad',
        f'{API} --> V: return (HTTP 400: campo incorrecto)', 'V --> A: indicar_el_campo_incorrecto()',
        'A -> V: ajustar_interruptores_y_guardar(mostrar_direccion, mostrar_telefono)'], reanudar='PUT /auth/privacidad'),
    4: dict(cortar='UPDATE Paciente SET privacidad_contacto', lineas=[*fallo_bd('Paciente'),
        '! Falla critica de persistencia al escribir los cambios',
        f'{API} --> V: return (HTTP 500: cambios no guardados)', 'V --> A: notificar_no_guardado_y_restaurar_valores_previos()',
        'A -> V: ajustar_interruptores_y_guardar(mostrar_direccion, mostrar_telefono)'], reanudar='PUT /auth/privacidad'),
  })

# ──────────────────────────── CU10 ────────────────────────────
CU10 = dict(id='CU10', nombre='Administrando catálogo de perfil profesional', actores=['Profesional'],
  vistas={'Profesional': 'V_Mi_Perfil_Publico'},
  participantes=[ACTOR, VISTA, *capa(ADP, CLOUD), *T('Profesional', 'Bitacora_Auditoria')],
  principal=[
    'A -> V: abrir_mi_perfil_publico()',
    f'V -> {API}: GET /profesionales/mi-perfil',
    *leer('obtener_perfil(usuario_id)', 'Profesional', 'foto_url, resena_curricular, areas_experticia, tipo_sede', '1 registro', 'return (perfil)'),
    f'{API} --> V: return (HTTP 200 OK: perfil y limites de formato)',
    'V --> A: mostrar_foto_resena_areas_y_modalidad()',
    'A -> V: seleccionar_fotografia(archivo)',
    f'V -> {API}: POST /profesionales/mi-perfil/foto (multipart)',
    f'{API} ->> {API}: validar_extension_y_peso(jpg|png|webp|heic, 5 MB)',
    *externo('subir_imagen(buffer, recorte 600x600)', CLOUD, 'POST /image/upload', 'return (secure_url)', 'return (secure_url)'),
    *actualizar('actualizar_foto(usuario_id, url)', 'Profesional', 'foto_url'),
    f'{API} --> V: return (HTTP 200 OK: foto_url)',
    'V --> A: mostrar_la_nueva_fotografia()',
    'A -> V: redactar_resena_areas_y_modalidad_y_guardar(resena, areas, modalidad)',
    'V ->> V: validar_largo_de_textos(1000 / 255)',
    'V ->> V: verificar_modalidad_seleccionada()',
    f'V -> {API}: PUT /profesionales/mi-perfil (resena, areas, tipo_sede)',
    f'{API} ->> {API}: validar_limites_y_modalidad()',
    *actualizar('actualizar_perfil(usuario_id, datos)', 'Profesional', 'resena_curricular, areas_experticia, tipo_sede'),
    *insertar('registrar_auditoria(ACTUALIZACION_PERFIL_PROFESIONAL, usuario_id, ip)', 'Bitacora_Auditoria'),
    f'{API} --> V: return (HTTP 200 OK: perfil actualizado)',
    'V --> A: mostrar_perfil_publicado_en_el_buscador()',
  ],
  excepciones={
    1: dict(cortar='abrir_mi_perfil', lineas=['! Error de comunicacion con el servidor al cargar el modulo',
        'V --> A: mostrar_error_con_opcion_de_reintentar()', 'A -> V: reintentar()'], reanudar='GET /profesionales/mi-perfil'),
    2: dict(cortar='SELECT foto_url', lineas=[*vacio('Profesional', '0 registros', 'sin perfil'),
        '! El perfil profesional no existe en la base de datos',
        f'{API} --> V: return (HTTP 404 PERFIL_NO_ENCONTRADO)', 'V --> A: informar_perfil_inexistente()',
        'A ->> A: contactar_al_administrador()', 'A -> V: reintentar_tras_regularizar_el_perfil()'], reanudar='GET /profesionales/mi-perfil'),
    3: dict(cortar='validar_extension_y_peso', lineas=['! Formato no permitido o peso superior al maximo definido',
        f'{API} --> V: return (HTTP 400 FORMATO_NO_PERMITIDO | 413 FOTO_MUY_PESADA)',
        'V --> A: mostrar_especificaciones_tecnicas_requeridas()', 'A -> V: seleccionar_fotografia(archivo_compatible)'],
        reanudar='POST /profesionales/mi-perfil/foto'),
    4: dict(cortar='validar_largo_de_textos', lineas=['! La resena o las areas superan el limite de caracteres',
        'V --> A: bloquear_guardado_y_resaltar_campo(limite)', 'A -> V: ajustar_la_longitud_del_texto_y_guardar(resena, areas)'],
        reanudar='validar_largo_de_textos'),
    5: dict(cortar='verificar_modalidad_seleccionada', lineas=['! Modalidad de atencion obligatoria omitida',
        'V --> A: impedir_guardado_y_senalar_campo_requerido()', 'A -> V: seleccionar_la_modalidad_y_guardar(DOMICILIO | ONLINE | AMBOS)'],
        reanudar='verificar_modalidad_seleccionada'),
    6: dict(cortar='UPDATE Profesional SET resena_curricular', lineas=[*fallo_bd('Profesional'),
        '! Falla de persistencia en la base de datos o en el repositorio de imagenes',
        f'{API} --> V: return (HTTP 500: cambios no grabados)', 'V --> A: notificar_cambios_no_grabados()',
        'A -> V: guardar_nuevamente()'], reanudar='PUT /profesionales/mi-perfil'),
  })

# ──────────────────────────── CU79 ────────────────────────────
CU79 = dict(id='CU79', nombre='Segregando interfaces según rol de acceso', actores=TRES,
  vistas={r: 'V_Inicio_Sesion' for r in TRES},
  participantes=[ACTOR, VISTA, *capa(SEG), *T('Usuario', 'Sesion_Usuario', 'Bitacora_Auditoria')],
  principal=[
    'A -> V: ingresar_credenciales(rut, contrasena)',
    f'V -> {API}: POST /auth/login (rut, contrasena)',
    *leer('obtener_usuario_y_rol(rut)', 'Usuario', 'usuario_id, contrasena_hash, rol_id (JOIN Rol)', '1 registro', 'return (usuario, rol)'),
    f'{API} -> {SEG}: comparar_hashes(contrasena, contrasena_hash)',
    f'{SEG} --> {API}: return (credenciales validas)',
    f'{API} -> {SEG}: generar_jwt(usuario_id, rol, jti)',
    f'{SEG} --> {API}: return (token de acceso)',
    *insertar('registrar_sesion(jti, dispositivo, ip)', 'Sesion_Usuario'),
    f'{API} --> V: return (HTTP 200 OK: token, rol = {{A}})',
    'V ->> V: decodificar_payload_jwt(rol)',
    'V ->> V: seleccionar_la_pila_de_pantallas({A})',
    'V --> A: renderizar_panel_{A}()',
    'A -> V: navegar_a_modulo(ruta habilitada del panel)',
    f'V -> {API}: GET /recurso (Authorization: Bearer token)',
    f'{API} -> {SEG}: verificar_token_y_rol([{{A}}])',
    f'{SEG} --> {API}: return (token valido, rol autorizado)',
    *leer('verificar_sesion_activa(jti)', 'Sesion_Usuario', 'activa', 'activa = TRUE', 'return (sesion vigente)'),
    f'{API} --> V: return (HTTP 200 OK: datos del modulo)',
    'V --> A: mostrar_el_modulo_habilitado()',
  ],
  excepciones={
    1: dict(cortar='comparar_hashes', lineas=['! Credenciales incorrectas',
        f'{SEG} --> {API}: return (credenciales invalidas)',
        *insertar('registrar_login_fallido(rut, ip)', 'Bitacora_Auditoria', " (accion = 'LOGIN_FALLIDO')"),
        f'{API} --> V: return (HTTP 401: credenciales invalidas)', 'V --> A: mostrar_error_de_credenciales()',
        'A -> V: reintentar_el_ingreso(rut, contrasena)'], reanudar='POST /auth/login'),
    2: dict(cortar='verificar_token_y_rol', lineas=['! Token JWT adulterado: la firma no coincide',
        f'{SEG} --> {API}: return (firma invalida)',
        *actualizar('revocar_la_sesion(jti)', 'Sesion_Usuario', 'activa', 'return (sesion revocada)'),
        f'{API} --> V: return (HTTP 401 TOKEN_INVALIDO)', 'V ->> V: limpiar_credenciales_locales()',
        'V --> A: forzar_el_cierre_de_sesion()', 'A ->> A: contactar_a_soporte_tecnico()'], reanudar='ingresar_credenciales'),
    3: dict(cortar='verificar_token_y_rol', lineas=['! El recurso esta reservado a otro rol',
        f'{SEG} --> {API}: return (rol no autorizado)',
        *insertar('registrar_bloqueo_rbac(usuario_id, ruta)', 'Bitacora_Auditoria', " (accion = 'BLOQUEO_ACCESO_RBAC')"),
        f'{API} --> V: return (HTTP 403: privilegios insuficientes)', 'V --> A: redirigir_al_panel_de_inicio()'],
        reanudar='navegar_a_modulo'),
    4: dict(cortar='SELECT activa FROM Sesion_Usuario', lineas=[*vacio('Sesion_Usuario', 'activa = FALSE', 'sesion revocada o token expirado'),
        '! Token expirado o sesion cerrada desde otro dispositivo',
        f'{API} --> V: return (HTTP 401 SESION_REVOCADA)', 'V ->> V: eliminar_el_token_local()',
        'V --> A: cerrar_la_sesion_con_aviso()'], reanudar='ingresar_credenciales'),
  })

if __name__ == '__main__':
    chrome = chrome_path()
    salida = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'salida')
    total = 0
    for cu in [CU06, CU07, CU08, CU09, CU10, CU79]:
        ruta, n = generar_cu(cu, os.path.join(salida, cu['id']), chrome=chrome, png=True)
        total += n; print(f"{cu['id']}: {n} paginas")
    print('total paginas', total)
